-- AlterTable
ALTER TABLE `BookedService` ADD COLUMN `raydiumPoolId` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `SplToken` ADD COLUMN `priceChange12hPercent` DOUBLE NULL,
    ADD COLUMN `priceChange1hPercent` DOUBLE NULL,
    ADD COLUMN `priceChange24hPercent` DOUBLE NULL,
    ADD COLUMN `priceChange2hPercent` DOUBLE NULL,
    ADD COLUMN `priceChange30mPercent` DOUBLE NULL,
    ADD COLUMN `priceChange4hPercent` DOUBLE NULL,
    ADD COLUMN `priceChange6hPercent` DOUBLE NULL,
    ADD COLUMN `v1hUSD` DOUBLE NULL,
    ADD COLUMN `v24hUSD` DOUBLE NULL,
    ADD COLUMN `v2hUSD` DOUBLE NULL,
    ADD COLUMN `v4hUSD` DOUBLE NULL,
    ADD COLUMN `v8hUSD` DOUBLE NULL,
    ADD COLUMN `vBuy1hUSD` DOUBLE NULL,
    ADD COLUMN `vBuy24hUSD` DOUBLE NULL,
    ADD COLUMN `vBuy2hUSD` DOUBLE NULL,
    ADD COLUMN `vBuy4hUSD` DOUBLE NULL,
    ADD COLUMN `vBuy8hUSD` DOUBLE NULL,
    ADD COLUMN `vSell1hUSD` DOUBLE NULL,
    ADD COLUMN `vSell24hUSD` DOUBLE NULL,
    ADD COLUMN `vSell2hUSD` DOUBLE NULL,
    ADD COLUMN `vSell4hUSD` DOUBLE NULL,
    ADD COLUMN `vSell8hUSD` DOUBLE NULL;

-- CreateTable
CREATE TABLE `LiquidityPoolInfo` (
    `poolId` VARCHAR(191) NOT NULL,
    `baseTokenMint` VARCHAR(191) NOT NULL,
    `quoteTokenMint` VARCHAR(191) NOT NULL,
    `liquidityUsd` DOUBLE NULL,
    `volume24h` DOUBLE NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`poolId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
