-- AlterTable
ALTER TABLE `BotCustomerWallet` MODIFY `type` ENUM('DEPOSIT', 'FEE_PAYER_FUND', 'SERVICE_FUNDING', 'VOLUME', 'FEES', 'MARKET_MAKING', 'SNIPING', 'SNIPING_FUNDING') NOT NULL;

-- AlterTable
ALTER TABLE `CompanyWallet` MODIFY `type` ENUM('DEPOSIT', 'FEE_PAYER_FUND', 'SERVICE_FUNDING', 'VOLUME', 'FEES', 'MARKET_MAKING', 'SNIPING', 'SNIPING_FUNDING') NOT NULL;
